### ISSUE TITLE
Build instructions are outdated and incomplete

### ISSUE THREAD

**Issue by E3V3A** [TresysTechnology/setools#135]
Hi Guys,
You're doing great hard work here, but there are a number of people around that are trying to build your tools according to your Wiki instructions for [Ubuntu](https://github.com/TresysTechnology/setools/wiki/SETools-4-on-Ubuntu-15) or Fedora. However, these seem outdated as they fail for the latest versions of these Linux distributions. Instead we have made a little more progress using [Linux Mint 17.3](https://www.linuxmint.com/download.php). At the end of the day we are hoping to get some tools that can also be used on Android. (Yeah, build instructions and patches for using on Android would be incredibly appreciated!)

In addition the differences for building using setools **v3** vs **v4** are very obscure. Is it dumb to start building and making changes to v3 since it is likely to be replaced by v4, soon?

Are you planning to make some updates on this?
Is there a way to contribute to your development here?

**Comment by pebenito** [comment]
The final 4.0.0 release is imminent, so I would suggest only using v4, if you can help it. There will be no further v3 releases.

If you can provide some errors, I can see what might be the problem. However, since the 4.0.0-beta release, the dependency for libsepol went to 2.5, which is not available on most distributions yet (I'm only aware of Fedora 24 Alpha and Gentoo having it, but did not thoroughly investigate). I've been updating the documentation to reflect this fact. Without seeing the errors, I'd guess that is the problem.

If you are using AOSP, then it already provides setools4 in the tree, though I don't know how up to date it is.

**Comment by pebenito** [comment]
Also, the build instructions for setools3 are completely different than for setools4, as v4 is almost completely rewritten and does not use autoconf and make, but instead uses Python setuptools.
