### ISSUE TITLE
seinfo --portcon ignores numbers inside a defined interval

### ISSUE THREAD

**Issue by milosmalik** [TresysTechnology/setools#171]
```
# rpm -qa setools\*
setools-console-4.1.0-3.fc26.x86_64
setools-python3-4.1.0-3.fc26.x86_64
# seinfo --portcon | grep 1023
   portcon tcp 512-1023 system_u:object_r:hi_reserved_port_t:s0
   portcon udp 512-1023 system_u:object_r:hi_reserved_port_t:s0
# seinfo --portcon 789

Portcon: 0
# seinfo --portcon | grep 5005
   portcon tcp 5004-5005 system_u:object_r:rtp_media_port_t:s0
   portcon udp 5004-5005 system_u:object_r:rtp_media_port_t:s0
# seinfo --portcon 5004

Portcon: 0
# seinfo --portcon 5005

Portcon: 0
# 
```

**Comment by pebenito** [comment]
This currently is working as intended. It is searching exact equality for the port range.

**Comment by doverride** [comment]
On Wed, Jun 21, 2017 at 03:15:44PM -0700, Chris PeBenito wrote:
> This currently is working as intended. It is searching exact equality for the port range.

Would be a nice feature to support because we can use grep to search for exact equality but we have no way to look for ports in a range easily

> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/TresysTechnology/setools/issues/171#issuecomment-310220780

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift
